require("custom.settings.settings")
require("custom.events")
require("custom.keymaps")
require("custom.commands")
require("custom.runCommand.runCommand")
require("custom.commandRegistry.commandRegistry")
